"""
Django settings for webKeepass project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import pymysql
pymysql.install_as_MySQLdb()


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'cnzxt%%!x+v4_0oec1l6wdu@^)++#qaq+mb0uzh5@7ec7$4n2$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['0.0.0.0', '127.0.0.1']


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
    'bootstrap3',
    'portal',
    'bootstrapform'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webKeepass.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webKeepass.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'webkeepass',
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'mysql'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'CONN_MAX_AGE': 600,
    }
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3')
    # }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

if DEBUG == False:
    ALLOWED_HOSTS = ['*']
    STATIC_ROOT = 'static'
    STATICFILES_DIRS = [os.path.join(BASE_DIR, '/static/')]

# 日志
LOGGING_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGGING_DIR):
    os.mkdir(LOGGING_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'loggers': {
        # 默认日志
        'webKeepass': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'handlers': ['default'],
            'propagate': True
        },
        'django': {
            'level': 'INFO',
            'handlers': ['django', 'console'],
            'propagate': False
        },
        'tasks': {
            'level': 'DEBUG' if DEBUG else 'INFO',
            'handlers': ['tasks'],
            'propagate': True
        }
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'default': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGGING_DIR, 'webKeepass.log'),
            'formatter': 'verbose'
        },
        'django': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGGING_DIR, 'django.log'),
            'formatter': 'verbose'
        },
        'tasks': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGGING_DIR, 'tasks.log'),
            'formatter': 'verbose'
        }
    },

    'formatters': {
        'verbose': {
            'format': '%(levelname)-6s [%(asctime)s] [%(process)d] [%(filename)8s:%(lineno)4d] %(message)s'
        },
        'simple': {
            'format': '%(asctime)s %(levelname)s %(message)s'
        }
    }
}

# 浏览器关闭就清除会话
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# 默认会话时间2小时
SESSION_COOKIE_AGE = 3600 * 2


##### 必填 #####
KEY = '3hyop5r21ac466e5'
EMAIL_HOST_USER = 'youremail@email.com'
EMAIL_HOST_PASSWORD = 'password'
EMAIL_USE_TLS = False # if use SSL
# EMAIL_PORT = 25
EMAIL_USE_SSL = True
EMAIL_PORT = 465
EMAIL_FROM = 'youremail@email.com'
EMAIL_HOST = 'smtp.email.com'
SITE_URL = 'website_url'


## 安全设置 ##
ADMIN_URL = 'admin' # admin
KEEP_QR_FILE = False # otp二维码是否保存成文件，默认不保存
TRY_LOGIN_FAILED_INTERVAL = 10 # 重试失败间隔时间,分钟
TRY_TIME = 3 # 重试次数


try:
    from .local_settings import *
except (ImportError, ImportWarning):
    print("\033[44;37m ###################################### \033[0m")
    print("\033[44;37m                                        \033[0m")
    print("\033[44;37m        No local settings exist         \033[0m")
    print("\033[44;37m     if you want to custom settings     \033[0m")
    print("\033[44;37m create local_settings.py and config it.\033[0m")
    print("\033[44;37m                                        \033[0m")
    print("\033[44;37m ###################################### \033[0m")

